database:
  user: "--"                  # Replace with your PostgreSQL username
  password: "--"          # Replace with your PostgreSQL password  
  host: "--"                  # Replace with your PostgreSQL host
  port: 5432                         # Replace with your PostgreSQL port
  database: "--"  

data:
  test_dataset: "data/test/testing_dataset.csv"

processing:
  size_threshold: 10000
  max_block_size: 500
  window_size: 100
  overlap: 50
  blocking_batch_size: 100000
  similarity_threshold: 2.0
  parquet_chunk_size: 1000000
  data_chunk_size: 50000        # Chunk size for reading CSV data
  prediction_chunk_size: 10000   # Chunk size for predictions to avoid memory issues

models:
  model_directory: "/test_pipeline/data/models"  # Path to trained models

# Output settings
output:
  predictions_directory: "data/predictions"
  processed_directory: "data/processed"
  
# Logging settings
logging:
  level: "INFO"
  file: "logs/test_app.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"