# Family Linkage Training Pipeline Configuration

database:
  user: "--"                   # Replace with your PostgreSQL username
  password: "--"          # Replace with your PostgreSQL password  
  host: "--"                  # Replace with your PostgreSQL host
  port: 5432                         # Replace with your PostgreSQL port
  database: "--"               # Replace with your database name

data:
  raw_dataset: data/raw/raw_data.csv
  raw_labels: data/raw/labels.csv     

processing:
  size_threshold: 10000
  max_block_size: 500
  window_size: 100
  overlap: 50
  blocking_batch_size: 100000
  similarity_threshold: 2.0
  parquet_chunk_size: 1000000

# Model hyperparameters for different relationship types
models:
  father:
    max_features: 9
    min_samples_leaf: 6
    n_estimators: 700
    n_jobs: -1
  partner:
    max_features: 6
    min_samples_leaf: 5
    n_estimators: 500
    n_jobs: -1
  mother:
    max_features: 12
    min_samples_leaf: 4
    n_estimators: 600
    n_jobs: -1
  twins:
    max_features: 4
    min_samples_leaf: 5
    n_estimators: 500
    n_jobs: -1
  sibling:
    max_features: 4
    min_samples_leaf: 2
    n_estimators: 500
    n_jobs: -1


output:
  models_directory: "data/models"
  plots_directory: "data/plots"
  logs_directory: "logs"

